app = "backend-devops-interview"
primary_region = "scl"

[build]
  dockerfile = "Dockerfile"

[deploy]
  release_command = "uv run python manage.py migrate"
  strategy = "canary"

[env]
  DEBUG = "False"
  ALLOWED_HOSTS = "backend-devops-interview.fly.dev"
  CSRF_TRUSTED_ORIGINS = "https://backend-devops-interview.fly.dev"

[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 1
  processes = ["app"]

  [[http_service.checks]]
    interval = "15s"
    timeout = "2s"
    grace_period = "10s"
    method = "GET"
    path = "/healthz"
