name: Deploy

on:
  push:
    branches: [main]

concurrency:
  group: production
  cancel-in-progress: false

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: production

    steps:
      - uses: actions/checkout@v4
      - uses: superfly/flyctl-actions/setup-flyctl@master
      - run: flyctl deploy --remote-only --depot=false --strategy rolling --wait-timeout 10m
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
